build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:latest
  amd64: ghcr.io/home-assistant/amd64-base:latest
  armv7: ghcr.io/home-assistant/armv7-base:latest
squash: false
labels:
  org.opencontainers.image.title: "Anytype Sync"
  org.opencontainers.image.description: "Self-hosted Anytype sync server"
  org.opencontainers.image.source: "https://github.com/lutzgo/hassio-anytype"
